### ISSUE TITLE
Bold and italics don't work

### ISSUE THREAD

**Issue by FilipeChagasDev** [apehex/lathex-template#1]
When using the LaTeX _\textbf_ and _\textit_ commands with the LatHex template, there is no effect.

**Comment by apehex** [comment]
Damn you're fast! How did you find my template @FilipeChagasDev ?
Think it's fixed now :)

**Comment by FilipeChagasDev** [comment]
> Damn you're fast! How did you find my template @FilipeChagasDev ?
> Think it's fixed now :)

I found it in the Overleaf template gallery as soon as I published it there.  Even, if possible, update the template there too.  Thanks for correcting!
